package com.freeme.provider;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig galleryFilesDaoConfig;

    private final GalleryFilesDao galleryFilesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        galleryFilesDaoConfig = daoConfigMap.get(GalleryFilesDao.class).clone();
        galleryFilesDaoConfig.initIdentityScope(type);

        galleryFilesDao = new GalleryFilesDao(galleryFilesDaoConfig, this);

        registerDao(GalleryFiles.class, galleryFilesDao);
    }

    public void clear() {
        galleryFilesDaoConfig.getIdentityScope().clear();
    }

    public GalleryFilesDao getGalleryFilesDao() {
        return galleryFilesDao;
    }

}
