package com.freeme.provider;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.List;

import de.greenrobot.dao.query.QueryBuilder;

/**
 * Entity mapped to table "GALLERY_FILES".
 */
public class GalleryFiles {

    private Long    id;
    /**
     * Not-null value.
     */
    private String  data;
    private Integer size;
    private Integer media_type;
    private String  display_name;
    private String  mime_type;
    private String  title;
    private Integer date_added;
    private Integer date_modified;
    private String  description;
    private String  picasa_id;
    private Integer duration;
    private String  artist;
    private String  album;
    private String  resolution;
    private Integer width;
    private Integer height;
    private Double  latitude;
    private Double  longitude;
    private Integer datetaken;
    private Integer orientation;
    private Integer mini_thumb_magic;
    private String  bucket_id;
    private String  bucket_display_name;
    private Integer story_bucket_id;
    private Integer is_hidden;
    private String  lbs_loc;
    private Integer  photo_voice_id;

    public GalleryFiles() {
    }

    public GalleryFiles(Long id) {
        this.id = id;
    }

    public GalleryFiles(Long id, String data, Integer size, Integer media_type, String display_name,
                        String mime_type, String title, Integer date_added, Integer date_modified,
                        String description, String picasa_id, Integer duration, String artist,
                        String album, String resolution, Integer width, Integer height,
                        Double latitude, Double longitude, Integer datetaken, Integer orientation,
                        Integer mini_thumb_magic, String bucket_id, String bucket_display_name,
                        Integer story_bucket_id, Integer is_hidden, String lbs_loc, Integer photo_voice_id) {
        this.id = id;
        this.data = data;
        this.size = size;
        this.media_type = media_type;
        this.display_name = display_name;
        this.mime_type = mime_type;
        this.title = title;
        this.date_added = date_added;
        this.date_modified = date_modified;
        this.description = description;
        this.picasa_id = picasa_id;
        this.duration = duration;
        this.artist = artist;
        this.album = album;
        this.resolution = resolution;
        this.width = width;
        this.height = height;
        this.latitude = latitude;
        this.longitude = longitude;
        this.datetaken = datetaken;
        this.orientation = orientation;
        this.mini_thumb_magic = mini_thumb_magic;
        this.bucket_id = bucket_id;
        this.bucket_display_name = bucket_display_name;
        this.story_bucket_id = story_bucket_id;
        this.is_hidden = is_hidden;
        this.lbs_loc = lbs_loc;
        this.photo_voice_id = photo_voice_id;
    }

    public static GalleryFiles getGalleryFiles(GalleryFilesDao galleryFilesDao, long id) {
        QueryBuilder<GalleryFiles> builder = galleryFilesDao.queryBuilder();
        builder.where(GalleryFilesDao.Properties.Id.eq(id));
        List<GalleryFiles> galleryFiles = builder.list();
        if (galleryFiles == null || galleryFiles.size() == 0) {
            return new GalleryFiles();
        }
        return galleryFiles.get(0);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getData() {
        return data;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setData(String data) {
        this.data = data;
    }

    public Integer getSize() {
        return size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

    public Integer getMedia_type() {
        return media_type;
    }

    public void setMedia_type(Integer media_type) {
        this.media_type = media_type;
    }

    public String getDisplay_name() {
        return display_name;
    }

    public void setDisplay_name(String display_name) {
        this.display_name = display_name;
    }

    public String getMime_type() {
        return mime_type;
    }

    public void setMime_type(String mime_type) {
        this.mime_type = mime_type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getDate_added() {
        return date_added;
    }

    public void setDate_added(Integer date_added) {
        this.date_added = date_added;
    }

    public Integer getDate_modified() {
        return date_modified;
    }

    public void setDate_modified(Integer date_modified) {
        this.date_modified = date_modified;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPicasa_id() {
        return picasa_id;
    }

    public void setPicasa_id(String picasa_id) {
        this.picasa_id = picasa_id;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    public String getResolution() {
        return resolution;
    }

    public void setResolution(String resolution) {
        this.resolution = resolution;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Integer getDatetaken() {
        return datetaken;
    }

    public void setDatetaken(Integer datetaken) {
        this.datetaken = datetaken;
    }

    public Integer getOrientation() {
        return orientation;
    }

    public void setOrientation(Integer orientation) {
        this.orientation = orientation;
    }

    public Integer getMini_thumb_magic() {
        return mini_thumb_magic;
    }

    public void setMini_thumb_magic(Integer mini_thumb_magic) {
        this.mini_thumb_magic = mini_thumb_magic;
    }

    public String getBucket_id() {
        return bucket_id;
    }

    public void setBucket_id(String bucket_id) {
        this.bucket_id = bucket_id;
    }

    public String getBucket_display_name() {
        return bucket_display_name;
    }

    public void setBucket_display_name(String bucket_display_name) {
        this.bucket_display_name = bucket_display_name;
    }

    public Integer getStory_bucket_id() {
        return story_bucket_id;
    }

    public void setStory_bucket_id(Integer story_bucket_id) {
        this.story_bucket_id = story_bucket_id;
    }

    public Integer getIs_hidden() {
        return is_hidden;
    }

    public void setIs_hidden(Integer is_hidden) {
        this.is_hidden = is_hidden;
    }

    public Integer getPhoto_voice_id_() {
        return photo_voice_id;
    }

    public void setPhoto_voice_id(Integer photo_voice_id) {
        this.photo_voice_id = photo_voice_id;
    }

    public String getLbs_loc() {
        return lbs_loc;
    }

    public void setLbs_loc(String lbs_loc) {
        this.lbs_loc = lbs_loc;
    }

    @Override
    public String toString() {
        return "GalleryFiles{" +
                "id=" + id +
                ", data='" + data + '\'' +
                ", size=" + size +
                ", media_type=" + media_type +
                ", display_name='" + display_name + '\'' +
                ", mime_type='" + mime_type + '\'' +
                ", title='" + title + '\'' +
                ", date_added=" + date_added +
                ", date_modified=" + date_modified +
                ", description='" + description + '\'' +
                ", picasa_id='" + picasa_id + '\'' +
                ", duration=" + duration +
                ", artist='" + artist + '\'' +
                ", album='" + album + '\'' +
                ", resolution='" + resolution + '\'' +
                ", width=" + width +
                ", height=" + height +
                ", latitude=" + latitude +
                ", longitude=" + longitude +
                ", datetaken=" + datetaken +
                ", orientation=" + orientation +
                ", mini_thumb_magic=" + mini_thumb_magic +
                ", bucket_id='" + bucket_id + '\'' +
                ", bucket_display_name='" + bucket_display_name + '\'' +
                ", story_bucket_id=" + story_bucket_id +
                ", is_hidden=" + is_hidden +
                ", lbs_loc='" + lbs_loc  + '\'' +
                ", photo_voice_id=" + photo_voice_id +
                '}';
    }
}
